# Data cleaning challenge 1

In [1]:
# Importing the needed Libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Checking for the imported files in the Directory
os.listdir('.')

['.config', 'fifa21 raw data v2.csv', 'sample_data']

##### Since we have our dataset available in the Directory, let's proceed to importing it into our notebook using pandas

In [4]:
# Reading the dataset into a pandas dataframe
fifa2 = pd.read_csv('fifa21 raw data v2.csv')
fifa2

<ipython-input-4-d6db27289bea>:2: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  fifa2 = pd.read_csv('fifa21 raw data v2.csv')

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

##### The data in column 76 may contain values of different data types, which could cause issues with data processing and analysis. To address this warning, you can either specify the data type of the 76th column when importing the data, or set the low_memory parameter to False when reading the data. Setting low_memory to False will load the entire dataset into memory,

In [5]:
# Reading the dataset again by setting low memory = False
fifa2 = pd.read_csv('fifa21 raw data v2.csv', low_memory=False)
fifa2

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

In [ ]:
# Checking the columns in the dataset
fifa2.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

##### Creating a copy of the Dataframe so we can commence the cleaning...

In [6]:
# Creating a copy of the Dataframe and making it display in full
fifa = fifa2.copy()
fifa.head(5)

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [ ]:
# Checking dataset details
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

##### Notice that some columns have irregular names, the next step is to rename those columns...

In [7]:
#renaming some columns in the Dataframe
fifa.rename(columns ={'↓OVA':'Overall(%)','POT':'Players_potential(%)', 'Height': 'Height(m)', 'Weight':'Weight(kg)',
                       'BOV': 'Best_overall(%)', 'W/F': 'Weak_foot_rating', 'SM': 'Skill_moves_rating', 
                        'A/W': 'Attacking_work_rate', 'D/W': 'Defensive_work_rate', 'IR': 'Injury_rating', 'PAC': 'Pace',
                       'SHO': 'Shooting', 'PAS': 'Pass_accuracy', 'DRI': 'Dribbling', 
                           'DEF': 'Defensive_ability', 'PHY': 'Physique'},inplace=True)
fifa.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       'Overall(%)', 'Players_potential(%)', 'Club', 'Contract', 'Positions',
       'Height(m)', 'Weight(kg)', 'Preferred Foot', 'Best_overall(%)',
       'Best Position', 'Joined', 'Loan Date End', 'Value', 'Wage',
       'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'Weak_foot_rating', 'Skill_moves_rating',
       'Attacking_work_rate', 'Defensive_work_rate', 'Injury_rating', 'Pace',
       'Shooting', 'Pass_accuracy', 'Dribbling', 'Defensive_ability',
       'Physique', 'Hits'],
      dtype='object')

In [ ]:
# Checking for columns with null values
pd.set_option('display.max_rows',None)
fifa.isna().sum()

ID                          0
Name                        0
LongName                    0
photoUrl                    0
playerUrl                   0
Nationality                 0
Age                         0
Overall(%)                  0
Players_potential(%)        0
Club                        0
Contract                    0
Positions                   0
Height(m)                   0
Weight(kg)                  0
Preferred Foot              0
Best_overall(%)             0
Best Position               0
Joined                      0
Loan Date End           17966
Value                       0
Wage                        0
Release Clause              0
Attacking                   0
Crossing                    0
Finishing                   0
Heading Accuracy            0
Short Passing               0
Volleys                     0
Skill                       0
Dribbling                   0
Curve                       0
FK Accuracy                 0
Long Passing                0
Ball Control                0
Movement                    0
Acceleration                0
Sprint Speed                0
Agility                     0
Reactions                   0
Balance                     0
Power                       0
Shot Power                  0
Jumping                     0
Stamina                     0
Strength                    0
Long Shots                  0
Mentality                   0
Aggression                  0
Interceptions               0
Positioning                 0
Vision                      0
Penalties                   0
Composure                   0
Defending                   0
Marking                     0
Standing Tackle             0
Sliding Tackle              0
Goalkeeping                 0
GK Diving                   0
GK Handling                 0
GK Kicking                  0
GK Positioning              0
GK Reflexes                 0
Total Stats                 0
Base Stats                  0
Weak_foot_rating            0
Skill_moves_rating          0
Attacking_work_rate         0
Defensive_work_rate         0
Injury_rating               0
Pace                        0
Shooting                    0
Pass_accuracy               0
Dribbling                   0
Defensive_ability           0
Physique                    0
Hits                     2595
dtype: int64

##### Notice that the 'Loan Date' and the 'Hits' columns both have some empty rows and we won't be needing {Name, Photourl, Playerurl, and Loan date} columns, so we proceed to removing these columns.

In [8]:
# Dropping these 4 columns 
fifa.drop(columns = ['LongName', 'playerUrl',	'photoUrl', 'Loan Date End'], inplace = True)
fifa.columns

Index(['ID', 'Name', 'Nationality', 'Age', 'Overall(%)',
       'Players_potential(%)', 'Club', 'Contract', 'Positions', 'Height(m)',
       'Weight(kg)', 'Preferred Foot', 'Best_overall(%)', 'Best Position',
       'Joined', 'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill',
       'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control',
       'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions',
       'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength',
       'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning',
       'Vision', 'Penalties', 'Composure', 'Defending', 'Marking',
       'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving',
       'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes',
       'Total Stats', 'Base Stats', 'Weak_foot_rating', 'Skill_moves_rating',
       'Attacking_work_rate', 'Defensive_work_rate', 'Injury_rating', 'Pace',
       'Shooting', 'Pass_accuracy', 'Dribbling', 'Defensive_ability',
       'Physique', 'Hits'],
      dtype='object')

In [ ]:
# Checking for duplicates
fifa.duplicated().sum()

0

> ###### No duplicates found

In [ ]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 73 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    18979 non-null  int64
 1   Name                  18979 non-null  object
 2   Nationality           18979 non-null  object
 3   Age                   18979 non-null  int64
 4   Overall(%)            18979 non-null  int64
 5   Players_potential(%)  18979 non-null  int64
 6   Club                  18979 non-null  object
 7   Contract              18979 non-null  object
 8   Positions             18979 non-null  object
 9   Height(m)             18979 non-null  object
 10  Weight(kg)            18979 non-null  object
 11  Preferred Foot        18979 non-null  object
 12  Best_overall(%)       18979 non-null  int64
 13  Best Position         18979 non-null  object
 14  Joined                18979 non-null  object
 15  Value                 18979 non-null  object
 16  Wage                  18979 non-null  object
 17  Release Clause        18979 non-null  object
 18  Attacking             18979 non-null  int64
 19  Crossing              18979 non-null  int64
 20  Finishing             18979 non-null  int64
 21  Heading Accuracy      18979 non-null  int64
 22  Short Passing         18979 non-null  int64
 23  Volleys               18979 non-null  int64
 24  Skill                 18979 non-null  int64
 25  Dribbling             18979 non-null  int64
 26  Curve                 18979 non-null  int64
 27  FK Accuracy           18979 non-null  int64
 28  Long Passing          18979 non-null  int64
 29  Ball Control          18979 non-null  int64
 30  Movement              18979 non-null  int64
 31  Acceleration          18979 non-null  int64
 32  Sprint Speed          18979 non-null  int64
 33  Agility               18979 non-null  int64
 34  Reactions             18979 non-null  int64
 35  Balance               18979 non-null  int64
 36  Power                 18979 non-null  int64
 37  Shot Power            18979 non-null  int64
 38  Jumping               18979 non-null  int64
 39  Stamina               18979 non-null  int64
 40  Strength              18979 non-null  int64
 41  Long Shots            18979 non-null  int64
 42  Mentality             18979 non-null  int64
 43  Aggression            18979 non-null  int64
 44  Interceptions         18979 non-null  int64
 45  Positioning           18979 non-null  int64
 46  Vision                18979 non-null  int64
 47  Penalties             18979 non-null  int64
 48  Composure             18979 non-null  int64
 49  Defending             18979 non-null  int64
 50  Marking               18979 non-null  int64
 51  Standing Tackle       18979 non-null  int64
 52  Sliding Tackle        18979 non-null  int64
 53  Goalkeeping           18979 non-null  int64
 54  GK Diving             18979 non-null  int64
 55  GK Handling           18979 non-null  int64
 56  GK Kicking            18979 non-null  int64
 57  GK Positioning        18979 non-null  int64
 58  GK Reflexes           18979 non-null  int64
 59  Total Stats           18979 non-null  int64
 60  Base Stats            18979 non-null  int64
 61  Weak_foot_rating      18979 non-null  object
 62  Skill_moves_rating    18979 non-null  object
 63  Attacking_work_rate   18979 non-null  object
 64  Defensive_work_rate   18979 non-null  object
 65  Injury_rating         18979 non-null  object
 66  Pace                  18979 non-null  int64
 67  Shooting              18979 non-null  int64
 68  Pass_accuracy         18979 non-null  int64
 69  Dribbling             18979 non-null  int64
 70  Defensive_ability     18979 non-null  int64
 71  Physique              18979 non-null  int64
 72  Hits                  16384 non-null  object
dtypes: int64(54), object(19)
memory usage: 10.6+ MB

##### We oserve that some columns have incorrect datatypes.
To change that, we'd need to first explore the column values to uncover any irregularity.

In [ ]:
# Checking for distinct values in the Height column
fifa['Height(m)'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [ ]:
# Checking for distinct values in the Weight column
fifa['Weight(kg)'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [ ]:
# Checking for irregular values in the Hits column
fifa['Hits'].head(10)

0     771
1     562
2     150
3     207
4     595
5     248
6     246
7     120
8    1.6K
9     130
Name: Hits, dtype: object

In [ ]:
# Checking for distinct values in the Release Clause column
fifa['Release Clause'].unique()

array(['€138.4M', '€75.9M', '€159.4M', ..., '€59K', '€35K', '€64K'],
      dtype=object)

In [ ]:
# Checking for distinct values in the Wage column
fifa['Wage'].unique()

array(['€560K', '€220K', '€125K', '€370K', '€270K', '€240K', '€250K',
       '€160K', '€260K', '€210K', '€310K', '€130K', '€350K', '€300K',
       '€190K', '€145K', '€195K', '€100K', '€140K', '€290K', '€82K',
       '€110K', '€230K', '€155K', '€200K', '€165K', '€95K', '€170K',
       '€105K', '€115K', '€150K', '€135K', '€55K', '€58K', '€81K', '€34K',
       '€120K', '€59K', '€90K', '€65K', '€56K', '€71K', '€18K', '€75K',
       '€47K', '€20K', '€84K', '€86K', '€74K', '€78K', '€27K', '€68K',
       '€85K', '€25K', '€46K', '€83K', '€54K', '€79K', '€175K', '€43K',
       '€49K', '€45K', '€38K', '€41K', '€39K', '€23K', '€51K', '€50K',
       '€87K', '€30K', '€14K', '€69K', '€31K', '€64K', '€53K', '€35K',
       '€21K', '€28K', '€17K', '€33K', '€70K', '€32K', '€89K', '€26K',
       '€40K', '€76K', '€72K', '€48K', '€36K', '€29K', '€60K', '€16K',
       '€37K', '€24K', '€52K', '€0', '€62K', '€73K', '€63K', '€19K',
       '€1K', '€66K', '€80K', '€12K', '€2K', '€42K', '€13K', '€900',
       '€57K', '€77K', '€61K', '€22K', '€67K', '€44K', '€15K', '€11K',
       '€8K', '€850', '€10K', '€88K', '€500', '€7K', '€6K', '€9K', '€5K',
       '€700', '€950', '€750', '€3K', '€650', '€600', '€4K', '€800',
       '€550'], dtype=object)

##### Next step is to write functions to convert these irregular values to a standard and consistent one for each columns.

##### Now let's write a function to clean up the 'Height' column

In [27]:
# creating a function to convert height to metres
def metre_conversion(Height):
    if 'cm' in Height:
        return float(Height.replace('cm', '')) / 100
    else:
        feet, inches = Height.split('\'')
        return round(float(feet) * 0.3048, 2) + round(float(inches.replace('"', '')) * 0.0254, 2)
    
    
# applying the function to the height column
fifa['Height(m)'] = fifa['Height(m)'].apply(metre_conversion)

# Checking for change 
fifa['Height(m)'].unique()

array([1.7 , 1.87, 1.88, 1.81, 1.75, 1.84, 1.91, 1.78, 1.93, 1.85, 1.99,
       1.73, 1.68, 1.76, 1.77, 1.83, 1.8 , 1.89, 1.79, 1.95, 1.72, 1.82,
       1.86, 1.92, 1.65, 1.94, 1.67, 1.96, 1.63, 1.9 , 1.74, 1.69, 1.71,
       1.97, 2.  , 1.66, 1.88, 1.64, 1.98, 1.91, 1.93, 1.62, 2.01, 1.58,
       1.61, 1.6 , 2.03, 1.57, 1.56, 2.02, 1.59, 2.06, 1.55])

##### Now let's write a function to clean up the 'Weight' column

In [9]:
# create a function to convert weight to kilogram
def kg_conversion(weight):
    if 'kg' in weight:
        return (weight.replace('kg', '')) 
    else:
        return round(float(weight.replace('lbs', '')) /2.20462, 2)
    
    
#applying the function to the weight column
fifa['Weight(kg)'] = fifa['Weight(kg)'].apply(kg_conversion)

# Checking for change  
fifa['Weight(kg)'].unique()

array(['72', '83', '87', '70', '68', '80', '71', '91', '73', '85', '92',
       '69', '84', '96', '81', '82', '75', '86', '89', '74', '76', '64',
       '78', '90', '66', '60', '94', '79', '67', '65', '59', '61', '93',
       '88', '97', '77', '62', '63', '95', '100', '58', 83.01, 81.19,
       78.02, 88.9, 79.83, 83.91, 77.11, 92.08, 76.2, 73.03, 66.22, 58.97,
       86.18, 78.93, 67.13, 74.84, 72.12, 87.09, 82.1, 63.05, 69.85,
       71.21, 73.94, '98', '103', '99', '102', '56', '101', '57', '55',
       '104', '107', '110', '53', '50', '54', '52'], dtype=object)

##### Now let's write a function to clean up the 'Wage', 'Release clause', and 'Value' columns

In [10]:
# define a function to remove '€' and convert the 'K' and 'M' to thousands and millions respectively
def convert_value(value_str):
    value = value_str.replace('€', '')
    if value_str.endswith ('K'):
        value = float(value[:-1]) * 1000
    elif value_str.endswith ('M'):
        value = float(value[:-1]) * 1000000
    else:
        value = float(value)
    if value.is_integer():
        return '{:.0f}'.format(value)
    else:
        return '{:.2f}'.format(value)

In [11]:
# apply the function to the wage, value and release clause columns
fifa[['Value', 'Wage', 'Release Clause']] = fifa[['Value', 'Wage', 'Release Clause']].applymap(convert_value)

In [ ]:
fifa[['Value', 'Wage', 'Release Clause']]

           Value    Wage Release Clause
0      103500000  560000      138400000
1       63000000  220000       75900000
2      120000000  125000      159400000
3      129000000  370000      161000000
4      132000000  270000      166500000
...          ...     ...            ...
18974     100000    1000          70000
18975     130000     500         165000
18976     120000     500         131000
18977     100000    2000          88000
18978     100000    1000          79000

[18979 rows x 3 columns]

##### Next is to clean up the Club column that has '\n\n'

In [12]:
#stripping the unnecessary characters in the club column
fifa['Club'] = fifa['Club'].str.replace('\n\n\n\n','')
fifa.head()

,ID,Name,Nationality,Age,Overall(%),Players_potential(%),Club,Contract,Positions,Height(m),...,Attacking_work_rate,Defensive_work_rate,Injury_rating,Pace,Shooting,Pass_accuracy,Dribbling,Defensive_ability,Physique,Hits
0,158023,L. Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,...,High,Medium,5 ★,91,85,86,94,36,59,595

##### Next is to clean up the star symbols that appear in the 'Weak_foot_rating', 'Skill_moves_rating', and 'Injury_rating' columns

In [13]:
#stripping the star character in columns Weak_foot_rating, Skill_moves_rating and Injury_rating
fifa[['Weak_foot_rating','Skill_moves_rating','Injury_rating']] = fifa[['Weak_foot_rating','Skill_moves_rating','Injury_rating']].apply(lambda x: x.str.replace('★',''))
fifa.head()

,ID,Name,Nationality,Age,Overall(%),Players_potential(%),Club,Contract,Positions,Height(m),...,Attacking_work_rate,Defensive_work_rate,Injury_rating,Pace,Shooting,Pass_accuracy,Dribbling,Defensive_ability,Physique,Hits
0,158023,L. Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,...,Medium,Low,5,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,...,High,Low,5,89,93,81,89,35,77,562
2,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,...,Medium,Medium,3,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,...,High,High,4,76,86,93,88,64,78,207
4,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,...,High,Medium,5,91,85,86,94,36,59,595

##### Next is to resolve the contract column by creating a new column called 'Contract_status' which shows players on active contract, on loan and free agents. Two new columns would be created for contract start year and contract end year for start and end of contract respectively.

In [14]:
# splitting the contract column and creating 2 separate Contract_start_year and Contract_end_year columns
fifa[['Contract_start_year', 'Contract_end_year']] = fifa['Contract'].str.split('~', expand=True)

fifa.head()

,ID,Name,Nationality,Age,Overall(%),Players_potential(%),Club,Contract,Positions,Height(m),...,Injury_rating,Pace,Shooting,Pass_accuracy,Dribbling,Defensive_ability,Physique,Hits,Contract_start_year,Contract_end_year
0,158023,L. Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,...,5,85,92,91,95,38,65,771,2004,2021
1,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,...,5,89,93,81,89,35,77,562,2018,2022
2,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,...,3,87,92,78,90,52,90,150,2014,2023
3,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,...,4,76,86,93,88,64,78,207,2015,2023
4,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,...,5,91,85,86,94,36,59,595,2017,2022

##### Next is to categorize players based on active contract, loan or free agents

In [15]:
# Creating the categories
conditions = [
    fifa['Contract'] == 'Free',
     fifa['Contract'].str.contains('On Loan')
]
values = ['Free agent', 'On Loan']

# using the numpy '.select()' to create a new column based on conditions and values
fifa['Contract_status'] = np.select(conditions, values, default = 'Active')

# display the result
fifa.head()

,ID,Name,Nationality,Age,Overall(%),Players_potential(%),Club,Contract,Positions,Height(m),...,Pace,Shooting,Pass_accuracy,Dribbling,Defensive_ability,Physique,Hits,Contract_start_year,Contract_end_year,Contract_status
0,158023,L. Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,...,85,92,91,95,38,65,771,2004,2021,Active
1,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,...,89,93,81,89,35,77,562,2018,2022,Active
2,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,...,87,92,78,90,52,90,150,2014,2023,Active
3,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,...,76,86,93,88,64,78,207,2015,2023,Active
4,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,...,91,85,86,94,36,59,595,2017,2022,Active

In [16]:
# Using the year in the contract column as contract_end_year for players on loan
fifa.loc[fifa['Contract_status'] == 'On Loan', 'Contract_end_year'] = fifa['Contract'].apply(lambda x: x.split(',')[-1].strip()[:4])

In [17]:
# dropping the contract and contract_start_year columns
fifa.drop(columns = ['Contract', 'Contract_start_year'], inplace = True)
fifa.head()

,ID,Name,Nationality,Age,Overall(%),Players_potential(%),Club,Positions,Height(m),Weight(kg),...,Injury_rating,Pace,Shooting,Pass_accuracy,Dribbling,Defensive_ability,Physique,Hits,Contract_end_year,Contract_status
0,158023,L. Messi,Argentina,33,93,93,FC Barcelona,"RW, ST, CF",170cm,72,...,5,85,92,91,95,38,65,771,2021,Active
1,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,"ST, LW",187cm,83,...,5,89,93,81,89,35,77,562,2022,Active
2,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,GK,188cm,87,...,3,87,92,78,90,52,90,150,2023,Active
3,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,"CAM, CM",181cm,70,...,4,76,86,93,88,64,78,207,2023,Active
4,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,"LW, CAM",175cm,68,...,5,91,85,86,94,36,59,595,2022,Active

##### Next is to handle the null/missing values and figures that contains 'K' in the hits column.

In [18]:
# creating a function to convert hits column
def convert_hits(hit):
    if pd.isna(hit):
        return 0
    elif isinstance(hit, int):
        return hit
    elif 'K' in hit:
        return int(float(hit.replace('K', '')) * 1000)
    else:
        return int(float(hit))

# applying the function the Hits column
fifa['Hits'] = fifa['Hits'].apply(convert_hits)

##### Next is to convert some column data types to the appropriate data types

In [19]:
# converting Weight and  Wage to integer
fifa[['Weight(kg)', 'Wage']] = fifa[['Weight(kg)', 'Wage']].astype(int) 

# converting Value and Release_clause to float
fifa[['Release Clause', 'Value']] = fifa[['Release Clause', 'Value']].astype(float)

# Converting ID column to string
fifa['ID'] = fifa['ID'].astype(str)

# converting Joined and Contract_end_year to datetime
fifa['Joined'] = pd.to_datetime(fifa['Joined'])

# converting contract_status to category
fifa[['Contract_status', 'Skill_moves_rating']] = fifa[['Contract_status', 'Skill_moves_rating']].astype('category')

In [20]:
# Converting Weak_foot_rating, Skill_moves_rating, Injury_rating, Attacking_work_rate and Defensive_work_rate to ordered category
ordinal_dict = {'Attacking_work_rate': ['Low', 'Medium', 'High'], 'Defensive_work_rate': ['Low', 'Medium', 'High'],
               'Weak_foot_rating': ['1 ', '2 ', '3 ', '4 ', '5 '], 'Injury_rating': ['1 ', '2 ', '3 ', '4 ', '5 ']}
for key, value in ordinal_dict.items():
    order = pd.api.types.CategoricalDtype(categories = value, ordered = True)
    fifa[key] = fifa[key].astype(order)

In [ ]:
# To confirm the datatype for each column
fifa.dtypes

ID                     object
Name                   object
Nationality            object
Age                     int64
Overall(%)              int64
                       ...
Defensive_ability       int64
Physique                int64
Hits                    int64
Contract_end_year      object
Contract_status      category
Length: 74, dtype: object

##### Based on the information on the FIFA website, attributes such as Attacking, Defending, Skill, Power, Defending, Mentality, Movement and Goalkeeping are the sum of other stats under them. Therefore, suming these up and dividing by 100 gives it a more consistent value.
* Attacking = Crossing + Heading Accuracy + Finishing + Short Passing + Short Passing + Volleys
*Skill = Dribbling + FK Accuracy + Curve + Long Passing + Ball Control
*Power = Shot Power + Jumping + Stamina + Strength + Long Shots
*Defending = Standing Tackle + Sliding Tackle + Marking
*Mentality = Aggression + Interceptions + Positioning + Vision + Penalties + Composure
*Movement = Acceleration + Sprint Speed + Agility + Reactions + Balance
*Goalkeeping = GK Diving + GK Handling + GK Kicking + GK Positioning + GK Reflexes
*Total Stats = Attacking + Skill + Power + Defending + Mentality + Movement + Goalkeeping

In [ ]:
fifa.columns

Index(['ID', 'Name', 'Nationality', 'Age', 'Overall(%)',
       'Players_potential(%)', 'Club', 'Positions', 'Height(m)', 'Weight(kg)',
       'Preferred Foot', 'Best_overall(%)', 'Best Position', 'Joined', 'Value',
       'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'Weak_foot_rating', 'Skill_moves_rating',
       'Attacking_work_rate', 'Defensive_work_rate', 'Injury_rating', 'Pace',
       'Shooting', 'Pass_accuracy', 'Dribbling', 'Defensive_ability',
       'Physique', 'Hits', 'Contract_end_year', 'Contract_status'],
      dtype='object')

In [21]:
# summing up each stats
fifa["Attacking"] = fifa2["Crossing"] + fifa2["Heading Accuracy"] + fifa2["Finishing"] + fifa2["Short Passing"] + fifa2["Volleys"]
fifa["Skill"] = fifa2["Dribbling"] + fifa2["FK Accuracy"] + fifa2["Curve"] + fifa2["Long Passing"] + fifa2["Ball Control"]
fifa["Power"] = fifa2["Shot Power"] + fifa2["Jumping"] + fifa2["Stamina"] + fifa2["Strength"] + fifa2["Long Shots"]
fifa["Defending"] = fifa2["Standing Tackle"] + fifa2["Sliding Tackle"] + fifa2["Marking"]
fifa["Mentality"] = fifa2["Aggression"] + fifa2["Interceptions"] + fifa2["Positioning"] + fifa2["Vision"] + fifa2["Penalties"] + fifa2["Composure"]
fifa["Goalkeeping"] = fifa2["GK Diving"] + fifa2["GK Handling"] + fifa2["GK Kicking"] + fifa2["GK Positioning"] + fifa2["GK Reflexes"]
fifa["Movement"] = fifa2["Acceleration"] + fifa2["Sprint Speed"] + fifa2["Agility"] + fifa2["Reactions"] + fifa2["Balance"]

In [22]:
# rounding each of the main skills / 100
fifa["Attacking"] = round(fifa["Attacking"]/5)
fifa["Skill"] = round(fifa["Skill"]/5)
fifa["Movement"] = round(fifa["Movement"]/5)
fifa["Power"] = round(fifa["Power"]/5)
fifa["Mentality"] = round(fifa["Mentality"]/6)
fifa["Defending"] = round(fifa["Defending"]/3)
fifa["Goalkeeping"] = round(fifa["Goalkeeping"]/5)

In [23]:
# Checking to view changes
fifa.head()

,ID,Name,Nationality,Age,Overall(%),Players_potential(%),Club,Positions,Height(m),Weight(kg),...,Injury_rating,Pace,Shooting,Pass_accuracy,Dribbling,Defensive_ability,Physique,Hits,Contract_end_year,Contract_status
0,158023,L. Messi,Argentina,33,93,93,FC Barcelona,"RW, ST, CF",170cm,72,...,5,85,92,91,95,38,65,771,2021,Active
1,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,"ST, LW",187cm,83,...,5,89,93,81,89,35,77,562,2022,Active
2,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,GK,188cm,87,...,3,87,92,78,90,52,90,150,2023,Active
3,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,"CAM, CM",181cm,70,...,4,76,86,93,88,64,78,207,2023,Active
4,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,"LW, CAM",175cm,68,...,5,91,85,86,94,36,59,595,2022,Active

##### Lastly, we Create a new column known as Body_mass_index (BMI) which can be used to evaluate a footballer's health and fitness. Formular for BMI is weight(kg) / (height(m))^2

In [28]:
# create a BmI column using the formular
fifa['Body_mass_index'] = fifa['Weight(kg)'] / (fifa['Height(m)'] ** 2)

# round the BMI column to two decimal places
fifa['Body_mass_index'] = fifa['Body_mass_index'].round(2)

In [29]:
fifa.head()

,ID,Name,Nationality,Age,Overall(%),Players_potential(%),Club,Positions,Height(m),Weight(kg),...,Pace,Shooting,Pass_accuracy,Dribbling,Defensive_ability,Physique,Hits,Contract_end_year,Contract_status,Body_mass_index
0,158023,L. Messi,Argentina,33,93,93,FC Barcelona,"RW, ST, CF",1.70,72,...,85,92,91,95,38,65,771,2021,Active,24.91
1,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,"ST, LW",1.87,83,...,89,93,81,89,35,77,562,2022,Active,23.74
2,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,GK,1.88,87,...,87,92,78,90,52,90,150,2023,Active,24.62
3,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,"CAM, CM",1.81,70,...,76,86,93,88,64,78,207,2023,Active,21.37
4,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,"LW, CAM",1.75,68,...,91,85,86,94,36,59,595,2022,Active,22.20

##### We finally have our data cleaned and ready for to be used for analysis...
so next, we'd save our data as a csv file.

In [30]:
# Converting to csv
fifa.to_csv('Fifa_21_data.csv', index = None)

In [32]:
# setting file up to be downloaded locally
from google.colab import files

files.download('Fifa_21_data.csv')